apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-application
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/hoanghd164/kustomize-demo.git
    targetRevision: HEAD
    path: kustomize-wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true